loki:
  auth_enabled: false 
  commonConfig:
    path_prefix: /var/loki
    replication_factor: 1
  storage_config:
    boltdb_shipper:
      active_index_directory: /var/loki/boltdb-shipper-active
      cache_location: /var/loki/boltdb-shipper-cache
      cache_ttl: 24h
      shared_store: s3
    aws:
      bucketnames: loki-storage
      region: eu-west-3
      s3forcepathstyle: false
  storage:
    bucketNames:
      chunks: loki-storage
      ruler: loki-storage
      admin: loki-storage
    type: s3
    s3:
      s3: s3://loki-storage
      endpoint: null
      region: null
      secretAccessKey: null
      accessKeyId: null
      s3ForcePathStyle: false
      insecure: false
      http_config: {}
  schemaConfig:
    configs:
      - from: 2020-07-01
        store: boltdb-shipper
        object_store: s3
        schema: v11
        index:
          prefix: index_
          period: 24h
  compactor:
    retention_enabled: true
    working_directory: /var/loki/compactor
    compaction_interval: 10m
    shared_store: s3
    retention_delete_delay: 2h
    retention_delete_worker_count: 150
  limits_config:
    enforce_metric_name: false
    max_cache_freshness_per_query: 10m
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    split_queries_by_interval: 15m
    per_stream_rate_limit: 512M
    per_stream_rate_limit_burst: 1024M
    cardinality_limit: 200000
    ingestion_burst_size_mb: 1000
    ingestion_rate_mb: 10000
    max_entries_limit_per_query: 1000000
    max_label_value_length: 20480
    max_label_name_length: 10240
    max_label_names_per_series: 300
tableManager:
  retention_deletes_enabled: true
  retention_period: 1488h
serviceAccount:
  annotations: {}
  name: grafana-loki-sa
write:
  replicas: 2
read:
  replicas: 2
monitoring:
  serviceMonitor:
    enabled: true
  selfMonitoring:
    grafanaAgent:
      installOperator: false
gateaway:
  basicAuth:
    enabled: true
    username: admin
    password: admin
ingress:
  enabled: false
  ingressClassName: alb
  hosts:
  - loki.solcomputing.net